services:
  # ===========================================================================
  # PostgreSQL
  # ===========================================================================
  postgres:
    image: postgres:18-alpine
    container_name: taskforge-postgres
    restart: unless-stopped

    # ports:
    #   - "${POSTGRES_PORT:-5432}:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - taskforge-network


  # ===========================================================================
  # Redis
  # ===========================================================================
  redis:
    image: redis:8-alpine
    container_name: taskforge-redis
    restart: unless-stopped

    # ports:
    #   - "${REDIS_PORT:-6379}:6379"

    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --requirepass
      - "${REDIS_PASSWORD}"

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    volumes:
      - redis_data:/data
      - ./infrastructure/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "${REDIS_PASSWORD}",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - taskforge-network


  # ===========================================================================
  # Task Forge API
  # ===========================================================================
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: taskforge
    restart: unless-stopped

    environment:
      # -----------------------------------------------------------------------
      # Application
      # -----------------------------------------------------------------------
      APP_PORT: ${APP_PORT}
      APP_MODE: ${APP_MODE}
      APP_LOGGING_LEVEL: ${APP_LOGGING_LEVEL}
      APP_ENCRYPTION_KEY: ${APP_ENCRYPTION_KEY}

      # -----------------------------------------------------------------------
      # Authentication
      # -----------------------------------------------------------------------
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_EXPIRY: ${APP_JWT_EXPIRY}

      # -----------------------------------------------------------------------
      # PostgreSQL
      # -----------------------------------------------------------------------
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      # -----------------------------------------------------------------------
      # Migrations
      # -----------------------------------------------------------------------
      MIGRATIONS_AUTO: ${MIGRATIONS_AUTO}
      MIGRATION_DB_USER: ${MIGRATION_DB_USER}
      MIGRATION_DB_PASSWORD: ${MIGRATION_DB_PASSWORD}

      # -----------------------------------------------------------------------
      # Redis
      # -----------------------------------------------------------------------
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      # -----------------------------------------------------------------------
      # EMAIL
      # -----------------------------------------------------------------------
      EMAIL_MODE: ${EMAIL_MODE:-smtp}
      # MAILTRAP
      MAILTRAP_API_KEY: ${MAILTRAP_API_KEY}
      MAILTRAP_DOMAIN: ${MAILTRAP_DOMAIN:-hello@demomailtrap.co}
      MAILTRAP_NAME: ${MAILTRAP_NAME:-task-forge}
      # SMTP
      SMTP_HOST: ${SMTP_HOST:-task-forge}
      SMTP_PORT: ${SMTP_PORT:-1025}
      SMTP_FROM: ${SMTP_FROM:-yourapp@example.com}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

    ports:
      - "${APP_PORT}:9099"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - taskforge-network


  # ---------------------------------------------------------------------------
  # Mailpit
  # ---------------------------------------------------------------------------
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025" # SMTP порт (сюда будет отправлять сообщение)
      - "8025:8025" # Web UI — тут смотреть письма
    environment:
      MP_SMTP_BIND_ADDR: 0.0.0.0:1025
      MP_SMTP_AUTH_ACCEPT_ANY: "true" # ← принимает любые логин/пароль (или пустые)
      MP_SMTP_AUTH_ALLOW_INSECURE: "true" # ← разрешает AUTH без TLS
      MP_SMTP_REQUIRE_STARTTLS: "false" # можно добавить явно
      MP_SMTP_REQUIRE_TLS: "false"
    networks:
      - taskforge-network
    restart: unless-stopped


# ============================================================================
# VOLUMES
# ============================================================================
volumes:
  postgres_data:
    driver: local

  redis_data:
    driver: local


# ============================================================================
# NETWORK
# ============================================================================
networks:
  taskforge-network:
    driver: bridge
    name: taskforge-network
  

